<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>alog</string>
	</array>
	<key>name</key>
	<string>Android log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?V/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?D/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Info</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?I/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warning</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?W/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?E/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assert</string>
			<key>match</key>
			<string>^((\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+)?A/[a-zA-z0-9\-_ +.]*(\(\s*\d+\))?:)(.*$)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>^(V\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>^(D\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Info</string>
			<key>match</key>
			<string>^(I\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warning</string>
			<key>match</key>
			<string>^(W\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>^(E\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assert</string>
			<key>match</key>
			<string>^(A\(\s*\d+\)).*(\([a-zA-z0-9\-_ +.]*\))$</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ V [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ D [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Info</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ I [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warning</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ W [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ E [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assert</string>
			<key>match</key>
			<string>^(\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+\s+\d+ A [a-zA-z0-9\-_ +.]*:)(.*$)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ V/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ D/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Info</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ I/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warning</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ W/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ E/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assert</string>
			<key>match</key>
			<string>^(\[ \d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d:?\s+\d+:\s+\d+ A/[a-zA-z0-9\-_ +.]* \])</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Default</string>
			<key>match</key>
			<string>^.*$</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.alog</string>
	<key>uuid</key>
	<string>624215ee-ffd7-4cce-af50-e4e4dc43d58b</string>
</dict>
</plist>
