<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>alog</string>
	</array>
	<key>name</key>
	<string>Android log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>(^V.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Debug</string>
			<key>match</key>
			<string>(^D.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Informations</string>
			<key>match</key>
			<string>(^I.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warnings</string>
			<key>match</key>
			<string>(^W.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Errors</string>
			<key>match</key>
			<string>(^E.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.emp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Asserts</string>
			<key>match</key>
			<string>(^A.*\(.*\):)(.*$)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.alog</string>
	<key>uuid</key>
	<string>624215ee-ffd7-4cce-af50-e4e4dc43d58b</string>
</dict>
</plist>
