<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ilog</string>
	</array>
	<key>name</key>
	<string>iOS log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Verbose</string>
			<key>match</key>
			<string>(^.*&lt;&gt;:)(.*$)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Notice</string>
			<key>match</key>
			<string>(^.*&lt;Notice&gt;:)(.*$)</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Warnings</string>
			<key>match</key>
			<string>(^.*&lt;Warning&gt;:)(.*$)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Errors</string>
			<key>match</key>
			<string>(^.*&lt;Error&gt;:)(.*$)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ilog</string>
	<key>uuid</key>
	<string>626215ee-ffd7-4cce-af50-e4e4dc43d58b</string>
</dict>
</plist>
